### ISSUE TITLE
How to stop server?

### ISSUE THREAD

**Issue by vko-online** [typicode/jsonplaceholder#14]
Everytime i start it, it throws error, Address in use, Don't want to change port everytime =(

**Comment by typicode** [comment]
What's your OS?

**Comment by typicode** [comment]
Actually ctrl-C should be enough. But if it says Address in use, you already have a process listening on port 3000.

It may be another instance of jsonplaceholder or some other development server (since port 3000 is quite common).

You should try to find if there's already a running jsonplaceholder server and kill it. Or if you have a server listening on port 3000, start jsonplaceholder on another port.

**Comment by vko-online** [comment]
I attached it to `gulp serve`, and when i run everytime it throws EADDRINUSE is there any command to shutdown server by script? So when i press Ctrl+C, json-server will shutdown with `gulp serve`

**Comment by gunjotSinghMansa** [comment]
Hi @vko-online ,

Did you get any answer for this?

**Comment by Ashish0019** [comment]
I faced the same issue  i forgot to`ctrl+c`, before closing the terminal, now it's giving EADDRINUSE for the same port.
**how to stop this server manually**
some what like `ps aux | grep gulp` in mac

_Don't wanna change port or restart the system_

**Comment by dmbdesignpdx** [comment]
Not sure if this too late or if this is even the solution to the problem you are experiencing, but here it goes:

If this is the error you're getting or something similar:
`Error:  Address already in use - bind(2)`

Type in the command line: 
`lsof -wni tcp:[port]`
where **[port]** is the port number that's in conflict

If that port is in conflict, there should be list of one or more uses. To stop them, type 
`kill -9 [PID]`
where **[PID]** is the process ID indicated by the column title "PID".

That should do it.

**Comment by typicode** [comment]
Thanks for the answers @Ashish0019 and @dmbdesignpdx, didn't know about `lsof -wni tcp:[port]` 👍 :)
