### ISSUE TITLE
Https

### ISSUE THREAD

**Issue by MassiveZergInc** [typicode/jsonplaceholder#18]
Hello,

would be nice if you can activate https on your webserver.

**Comment by typicode** [comment]
Hi @MassiveZergInc,

You mean in development or production?
Why do you need it?

**Comment by typicode** [comment]
Sorry for the previous response, I was thinking about another project.

**Comment by typicode** [comment]
I agree. There's [letsencrypt](https://letsencrypt.org/) that arrives soon. I'll see how it can be added when the service opens.

But on the other hand, I'm a bit curious about the use-case for https since JSON Placeholder uses mostly dummy data?

You can also run the server locally using `json-server http://jsonplaceholder.typicode.com/db`, if you don't want to send data on the Internet.

**Comment by georgir** [comment]
Hi, the use-case is just when the client app is running on https for whatever reason, it can not make requests to http.
I see you already have https though it is using a certificate for a different domain - *.herokuapp.com
People that want to test can just visit the frontpage through https and add an exception to accept the certificate despite the inconsistency, and after that the ajax calls should be working fine.

**Comment by typicode** [comment]
@georgir Amazing, didn't know this "trick" :+1: !

**Comment by dwiyatci** [comment]
The workaround from @georgir works for me! :hand: @typicode Any update on this? The use case for me is to fiddle around from httpS://jsfiddle.net/ :-)

**Comment by georgir** [comment]
https://jsonplaceholder.herokuapp.com/ works too, and the SSL cert is exactly for that.

**Comment by typicode** [comment]
https://jsonplaceholder.typicode.com :)
