### ISSUE TITLE
JSON Placeholder API not Reflecting POST or PUT

### ISSUE THREAD

**Issue by dilkROM** [typicode/jsonplaceholder#42]
Hey there, apologies if this is the wrong place to ask, but currently I am trying to send a POST and/or PUT request to the JSON Placeholder hosted on typicode. My understanding is that it's up, live, as a free resource to run tests. I get a proper response from my request but then using GET to fetch the changed results shows no changes. What is going on here?

Results of my POST:

```
{
  "title": "Hey Heidi!",
  "body": "This was a POST test!",
  "userId": 1,
  "id": 101
}%    
```

Results of GET request to id 101:

```
{}
```

Any help would be much appreciated, and thank you for this great resource.

**Comment by alexandermikuta** [comment]
Did you add the Content-Type-Header?

**Comment by typicode** [comment]
Hi @dilkROM,

Sorry for the delay.

Since it's used by many, GET should always return the same thing for everyone so JSONPlaceholder fakes POST and PUT writing.

It returns a new resource but if you list resources again, you won't find it.

So everything is "normal". To be able to write for real, you can JSON Server locally.
