### ISSUE TITLE
Unable to post a new user

### ISSUE THREAD

**Issue by antoinePinloche** [typicode/jsonplaceholder#78]
Hello !

Since today, I'm not able to see a user that I posted.
Here's my code 

```
    fetch("https://jsonplaceholder.typicode.com/users", {
      method: "POST",
      body: JSON.stringify({
        firstName: "foo",
        lastName: "bar",
        userId: 1
      }),
      headers: {
        "Content-type": "application/json; charset=UTF-8"
      }
    })
      .then(response => response.json())
      .then(json => console.log(json));

    fetch("https://jsonplaceholder.typicode.com/users", {
      headers: {
        "Content-type": "application/json; charset=UTF-8"
      }
    })
      .then(responseGet => responseGet.json())
      .then(jsonGet => console.log(jsonGet));
```

For my first console.log(json) i get properly my user with id: 11, firstName etc.
But, for my second console.log(jsonGet), i only get the 10 users which are already in the API, but not the user I posted.

Any help would be appreciated ! :)

**Comment by typicode** [comment]
Hello @antoinePinloche!

Thanks for the feedback. It actually works as "expected".

Since JSONPlaceholder is a shared API used by many, modifications are faked (POST, PUT, PATCH) and resources are read-only. This is to avoid user "A" creating new resources and having user "B" impacted by  them.

If you need to make changes and persist them between calls, you can run [JSON Server](https://github.com/typicode/json-server) locally.

Hope it clarifies things 👍
